export { default as HomePageView } from "./HomePageView";
export { default as CaesarCipherView } from "./CaesarCipherView";
export { default as VigenereCipherView } from "./VigenereCipherView";
export { default as RC4View } from "./RC4View";
export { default as ArticlesView } from "./ArticlesView";
export { default as LogInView } from "./LogInView";
export { default as SignUpView } from "./SignUpView"
export { default as UserProfileView } from "./UserProfileView"
export { default as Quiz0View } from "./Quiz0View"
export { default as DESView } from "./DESView"
export { default as RC4QuizView } from "./RC4QuizView"
export { default as VeriticationView } from "./VerificationView"
export { default as SideNavigation } from "./SideNavigation"
